# Generated by Django 5.0.6 on 2026-05-30 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={},
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('episode', 'Episode'), ('documentary', 'Documentary'), ('standup', 'Standup'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional rating from 1 to 10', null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='reaction',
            field=models.CharField(choices=[('liked', 'Liked'), ('neutral', 'Neutral'), ('disliked', 'Disliked')], default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
