# Generated by Django 5.0.6 on 2026-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_watchhistory_options_watchhistory_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='mood',
            field=models.CharField(choices=[('chill', 'Chill'), ('funny', 'Funny'), ('intense', 'Intense'), ('dark', 'Dark'), ('smart', 'Smart'), ('background', 'Background'), ('date_night', 'Date Night'), ('family', 'Family'), ('weird', 'Weird'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='recommended_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='would_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('episode', 'Episode'), ('documentary', 'Documentary'), ('standup', 'Standup'), ('sports', 'Sports'), ('youtube', 'YouTube'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
